"""Pydantic models for the BrainRotStudy pipeline."""

from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class JobStatus(str, Enum):
    """Job execution status."""
    QUEUED = "queued"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class JobStage(str, Enum):
    """Pipeline stages."""
    EXTRACT = "extract"
    SCRIPT = "script"
    TIMELINE = "timeline"
    ASSETS = "assets"
    VOICE = "voice"
    CAPTIONS = "captions"
    RENDER = "render"
    FINALIZE = "finalize"


class Preset(str, Enum):
    """Video generation presets affecting pacing and style."""
    FAST = "FAST"
    BALANCED = "BALANCED"
    EXAM = "EXAM"


class CaptionStyle(str, Enum):
    """Caption display styles."""
    BOLD = "BOLD"
    MINIMAL = "MINIMAL"


class MotionStyle(str, Enum):
    """Visual motion styles for video segments."""
    PAN_SLOW = "pan_slow"
    ZOOM_IN = "zoom_in"
    ZOOM_OUT = "zoom_out"
    STATIC = "static"


# ============= Stage 1: Extracted Slides =============

class SlideData(BaseModel):
    """Single slide extracted from PDF/PPTX."""
    index: int
    title: str = ""
    bullets: list[str] = Field(default_factory=list)
    raw_text: str = ""
    rendered_image: Optional[str] = None
    images: list[str] = Field(default_factory=list)


class SlidesExtracted(BaseModel):
    """Collection of slides extracted from a document."""
    slides: list[SlideData] = Field(default_factory=list)


# ============= Stage 2: Script Plan =============

class ScriptLine(BaseModel):
    """Single line of narration in the script."""
    t: float = Field(description="Start time in seconds")
    line: str
    emphasis: list[str] = Field(default_factory=list)
    source_slide_indices: list[int] = Field(default_factory=list)


class VisualCue(BaseModel):
    """Visual cue for asset fetching."""
    t: float = Field(description="Time in seconds when visual should appear")
    query: str
    type: str = "image"
    priority: int = 1


class ScriptPlan(BaseModel):
    """Complete script plan generated by LLM."""
    title: str
    hook: str
    style_preset: Preset
    script_lines: list[ScriptLine] = Field(default_factory=list)
    visual_cues: list[VisualCue] = Field(default_factory=list)
    study_takeaways: list[str] = Field(default_factory=list)


# ============= Stage 4: Assets Manifest =============

class AssetItem(BaseModel):
    """Single asset item with attribution."""
    id: str
    type: str = Field(description="image, bg_video, or music")
    path: str
    source_url: Optional[str] = None
    title: str = ""
    author: str = ""
    license: str = ""
    attribution: str = ""


class AssetsManifest(BaseModel):
    """Collection of assets used in the video."""
    items: list[AssetItem] = Field(default_factory=list)


# ============= Stage 6: Captions =============

class WordTiming(BaseModel):
    """Word-level timing for captions."""
    text: str
    start: float
    end: float


class LineTiming(BaseModel):
    """Line-level timing for captions."""
    text: str
    start: float
    end: float


class CaptionsWordLevel(BaseModel):
    """Word and line level caption timings."""
    words: list[WordTiming] = Field(default_factory=list)
    lines: list[LineTiming] = Field(default_factory=list)


# ============= Stage 3/7: Timeline Plan =============

class TimelineSegment(BaseModel):
    """Single segment of the video timeline."""
    index: int
    start_sec: float
    end_sec: float
    narration_text: str
    emphasis_words: list[str] = Field(default_factory=list)
    visual_asset_path: Optional[str] = None
    slide_frame_index: Optional[int] = None
    caption_style: CaptionStyle = CaptionStyle.BOLD
    motion_style: MotionStyle = MotionStyle.STATIC


class TimelinePlan(BaseModel):
    """Complete video timeline."""
    segments: list[TimelineSegment] = Field(default_factory=list)
    total_duration_sec: float = 60.0


# ============= Job Management =============

class JobOptions(BaseModel):
    """Options for job creation."""
    length_sec: int = Field(default=60, description="Target video length (60 or 90)")
    preset: Preset = Preset.BALANCED
    caption_style: CaptionStyle = CaptionStyle.BOLD
    voice_id: str = "default"
    export_extras: bool = False


class JobCreate(BaseModel):
    """Request body for creating a topic-only job."""
    topic: Optional[str] = None
    outline: Optional[str] = None
    options: JobOptions = Field(default_factory=JobOptions)


class JobArtifacts(BaseModel):
    """URLs for job artifacts."""
    video_url: Optional[str] = None
    srt_url: Optional[str] = None
    notes_url: Optional[str] = None
    anki_url: Optional[str] = None


class JobResponse(BaseModel):
    """Response for job status endpoint."""
    job_id: str
    status: JobStatus
    stage: Optional[JobStage] = None
    progress_pct: int = 0
    title: str = ""
    created_at: datetime
    updated_at: datetime
    artifacts: Optional[JobArtifacts] = None
    error_message: Optional[str] = None


class SSEEvent(BaseModel):
    """Server-Sent Event payload."""
    job_id: str
    stage: str
    progress_pct: int
    message: str
    log_tail: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class JobMetadata(BaseModel):
    """Metadata stored in the job directory."""
    job_id: str
    status: JobStatus = JobStatus.QUEUED
    stage: Optional[JobStage] = None
    progress_pct: int = 0
    title: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    input_type: str = "topic"  # "topic" or "file"
    input_filename: Optional[str] = None
    options: JobOptions = Field(default_factory=JobOptions)
    error_message: Optional[str] = None
